---
title: "BUAN_5310 Group_Project"
author: "Florence Yan"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: '3'
  html_notebook:
    number_sections: yes
    toc: yes
    toc_depth: 3
    toc_float: yes
---

```{r message = FALSE, echo = FALSE, error = FALSE}
# Clear environment of variables and functions
rm(list = ls(all = TRUE)) 
# Clear environmet of packages
if(is.null(sessionInfo()$otherPkgs) == FALSE)lapply(paste("package:", names(sessionInfo()$otherPkgs), sep=""), detach, character.only = TRUE, unload = TRUE)
```


# 1. Data Loading and Preperation
```{r message = FALSE, echo = FALSE, error = FALSE}
library(tidyverse)
library(GGally)
library(janitor)
library(kableExtra)
library(htmlTable)
library(ggplot2)
```


```{r}
# Load data
acs <- read.csv('airport_choice_survey.csv')
traffic <- read.csv('traffic.csv')
province <- read.csv('province.csv')
price <- read.csv('price.csv')
```


```{r}
# Rename columns in R
names(acs)[1]<-"ID"
names(price)[1] <- "Airport"
names(province)[1] <- "Airport"
names(province)[4] <- "Travel.time.min"
names(traffic)[1] <- "Airport"
```


```{r}
str(acs)
summary(acs)
```

```{r}
# Data cleaning
acs[2] <- ifelse(acs[2] == 1, 'ICN', 'GMP') 
  
acs[3] <- ifelse(acs[3] == 1, 'Korean',
           (ifelse(acs[3] == 2, 'Korean',
              (ifelse(acs[3] == 3, 'Korean', 'Foreign'))))
                   )
acs[4] <- ifelse(acs[4] <= 50 , '<=50', '>50')
acs[7] <- ifelse(acs[7] == 1, 'Leisure', 'Business')
```
